server:
  port: 8072

spring:
  config:
    import: "optional:configserver:http://configserver:8071/"
    
eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: "http://localhost:8070/eureka/"

security:
  oauth2:
    resourceserver:
      jwt:
        # Using issuer-uri allows Spring Security to automatically discover the JWK set URI
        issuer-uri: "http://keycloak:8080/realms/master"

