spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          # Using issuer-uri allows Spring Security to automatically discover the JWK set URI
          issuer-uri: "http://localhost:7080/realms/master"
eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: "http://localhost:8070/eureka/"

