build:
  version: "1.0"

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/invoicedb
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  flyway:
    locations: /db.migration
    sqlMigrationSuffixes: .sql
    url: jdbc:mysql://localhost:3306/invoicedb
    user: root
    password: root
    baseline-version: 0.0

invoices:
  message: "Welcome to Invoice Microservice related github docker APIs "
  contactDetails:
    name: "Andrew Pettigrew"
    email: "dummyemail@gmail.com"
  onCallSupport:
    - (555) 555-1234
    - (555) 523-1345
